# Requirements Gathering Activities

## Objectives

Requirements gathering activities were undertaken to:

* Identify workflow functionality required by prospective users.
* Develop detailed use cases.
* Understand workflow requirements and constraints.
* Inform prioritisation of the first and second workflow development tranches.

## Engagement Activities

| Activity        | Date          | Purpose                                |
| --------------- | ------------- | -------------------------------------- |
| Core team meetings     | May - July 2026   | General structure and background |
| Workshop 1      | 19 May 2026   | Scope, users and priorities            |
| Workshop 2      | 29 June 2026     | Workflow requirements and architecture |
| Survey      | July-August 2026?     | Outputs, validation and adoption       |
| Interviews / meetings      | May–July 2026 | Targeted stakeholder feedback          |
| Document review | Continuous    | Existing workflows and requirements    |




## Participants in stakeholder workshops

We had 32 participants in the first stakeholder workshop that involved ecosystem scientists, data analysts, government practitioners, research software engineers, data managers, and platform providers. We had 12 participants in the second workshop that targeted researchers with direct experience in ecosystem assessments.

## Meetings and interviews

We gathered feedback through participation in ... meetings with different participants.



Summarise:

* Government
* Researchers
* Ecologists
* Data scientists
* Platform providers
* Students/ECRs

## Key Themes

* Adaptability
* Reproducibility
* Documentation
* Interoperability
* Training
* FAIR compliance

