
# Prioritisation of Functionality – Second Tranche (Jan–Nov 2027)

## Tranche 2 Objective

The second tranche expands the workflow ecosystem beyond individual workflows to support discoverability, scaling, interoperability and broader community adoption. The focus shifts from workflow creation to workflow reuse and operationalisation. 

The main objective is to support and expand adaptation of workflows to new ecosystems and different purposes (UC03 and UC04). Development of new indicator workflows (UC02) will be enhanced and driven by ongoing research projects and assessments. 

Workflow development in this stage should follow the FAIR4RS and PID implementation plans, including full publication of workflows (UC05).

Integration of workflows into ongoing or planned assessments will continue to be explored (UC06). It is expected that ongoing asssessments will be the main drivers and motivation for selecting specific ecosystems and purposes for UC02, UC03 and UC04.

Scaling up assessment will be coupled with a larger focus on discoverability (UC07) through development of Work Package 5. 

The development of this tranche will allow multiple opportunities for training (UC08) and involvement of early career researchers and students. Particularly, the previous experience in development of reproducible indicator workflows from existing workflows (UC01) can be used for didactic purposes. Further development of tiered training materials for beginners, intermediate and advanced users will be complemented with more technical documentation for implementation and maintenance of platform functionality. At least one community event will be completed leading to publication of workshop outputs.
