project:
  type: book

book:
  title: "DRAFT: Ecosystem Indicator Workflows Development Plan"
  subtitle: "Requirements Gathering and Two-Year Development Roadmap"
  author:
    - "Ecosystem Indicators Workflows Project Team"
  date: last-modified

  chapters:
    - index.qmd
    - part: "Part I - Context"
      chapters:
        - 01-introduction.qmd
        - 02-requirements-gathering.qmd

    - part: "Part II - User Needs"
      chapters:
        - 03-user-groups.qmd
        - 04-user-requirements.qmd
        - 05-high-level-requirements.qmd

    - part: "Part III - Use Cases"
      chapters:
        - 06-use-cases.qmd
        - 07-prioritisation-method.qmd

    - part: "Part IV - Roadmap"
      chapters:
        - 08-roadmap-overview.qmd
        - 09-tranche-1.qmd
        - 10-tranche-2.qmd
        - 11-tranche-review.qmd

    - part: "Part V - Monitoring and Success"
      chapters:
        - 12-success-measures.qmd

    - part: "Appendices"
      chapters:
        - appendices/appendix-a-workshops.qmd
        - appendices/appendix-b-user-stories.qmd
        - appendices/appendix-c-traceability-matrix.qmd
  margin-header: |
    ![](assets/logo_CES.png){fig-align="center" height=66px}
  page-footer:
    left: "This site prepared by: [EIW project team](https://github.com/Ecosystem-Indicators-Workflows)"
    center: "![](/assets/unsw_new_logo.png){height=20px} We acknowledge the Bedegal and Gadigal peoples who are the Traditional Owners of the lands where UNSW Sydney is located. We pay our respects to Elders past and present."
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    number-depth: 3
  pdf:
    toc: true
    number-sections: true

  docx:
    toc: true
    number-sections: true

execute:
  echo: false
  warning: false
  message: false
